```{r}
url <- "https://github.com/DavidVarga1995/understat_data/archive/refs/heads/main.zip"
dest <- "./understat_data.zip"

download.file(url, dest)
unzip(dest)
```

```{r}
library(dplyr)
```

```{r}
library("ggpubr")
```

```{r}
all_shots <- read.csv('./understat_data-main/data/Bundesliga_2019/Bundesliga_shots_2019.csv')
```

```{r}
str(all_shots)
```

```{r}
summary(all_shots)
```

```{r}
normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}
```

```{r}
left_right <- function(x) {
  return (as.integer(x[2]) - as.integer(x[1]))
}
```

```{r}
# V2.0

all_shots_select <- select(all_shots, 'match_id', 'player_id', 'minute', 'situation', 'X', 'Y', 'shotType', 'result', 'xG')

shots_left <- filter(all_shots_select, all_shots_select$shotType == 'LeftFoot')
shots_right <- filter(all_shots_select, all_shots_select$shotType == 'RightFoot')
shots_head <- filter(all_shots_select, all_shots_select$shotType == 'Head')

shots_left_count <- filter(all_shots_select, all_shots_select$shotType == 'LeftFoot')
shots_right_count <- filter(all_shots_select, all_shots_select$shotType == 'RightFoot')
shots_head_count <- filter(all_shots_select, all_shots_select$shotType == 'Head')

shots_left_goal <- filter(all_shots_select, all_shots_select$shotType == 'LeftFoot' & all_shots_select$result == 'Goal')
shots_right_goal <- filter(all_shots_select, all_shots_select$shotType == 'RightFoot' & all_shots_select$result == 'Goal')
shots_head_goal <- filter(all_shots_select, all_shots_select$shotType == 'Head' & all_shots_select$result == 'Goal')

shots_left <- aggregate(list(xG_sum_l = shots_left$xG),
 by = list(player_id = shots_left$player_id),
  FUN = sum)

shots_right <- aggregate(list(xG_sum_r = shots_right$xG),
 by = list(player_id = shots_right$player_id),
  FUN = sum)

shots_head <- aggregate(list(xG_sum_h = shots_head$xG),
 by = list(player_id = shots_head$player_id),
  FUN = sum) 

shots_left_count <- aggregate(list(shots_count_l = shots_left_count$match_id),
 by = list(player_id = shots_left_count$player_id),
  FUN = length)

shots_right_count <- aggregate(list(shots_count_r = shots_right_count$match_id),
 by = list(player_id = shots_right_count$player_id),
  FUN = length)

shots_head_count <- aggregate(list(shots_count_h = shots_head_count$match_id),
 by = list(player_id = shots_head_count$player_id),
  FUN = length) 

shots_left_goal <- aggregate(list(goal_count_l = shots_left_goal$match_id),
 by = list(player_id = shots_left_goal$player_id),
  FUN = length)

shots_right_goal <- aggregate(list(goal_count_r = shots_right_goal$match_id),
 by = list(player_id = shots_right_goal$player_id),
  FUN = length)

shots_head_goal <- aggregate(list(goal_count_h = shots_head_goal$match_id),
 by = list(player_id = shots_head_goal$player_id),
  FUN = length) 

left_right_head <- merge(shots_left, shots_right, by = c("player_id"), all = TRUE)
left_right_head <- merge(left_right_head, shots_head, by = c("player_id"), all = TRUE)

left_right_head <- merge(left_right_head, shots_left_goal, by = c("player_id"), all = TRUE)
left_right_head <- merge(left_right_head, shots_right_goal, by = c("player_id"), all = TRUE)
left_right_head <- merge(left_right_head, shots_head_goal, by = c("player_id"), all = TRUE)

left_right_head <- merge(left_right_head, shots_left_count, by = c("player_id"), all = TRUE)
left_right_head <- merge(left_right_head, shots_right_count, by = c("player_id"), all = TRUE)
left_right_head <- merge(left_right_head, shots_head_count, by = c("player_id"), all = TRUE)

player_name <- select(all_shots, 'player', 'player_id')
player_name <- aggregate(list(c = player_name$player),
 by = list(player = player_name$player, player_id = player_name$player_id),
  FUN = length)
player_name <- select(player_name, 'player', 'player_id')

left_right_head <- merge(left_right_head, player_name, by = c("player_id"), all = TRUE)

left_right_head <- filter(left_right_head, shots_count_l != 0 & shots_count_r != 0)

left_right_head[is.na(left_right_head)] <- 0

left_right_head$difference_shots <- apply(left_right_head[8:9], 1, function(x) left_right(x))
left_right_head$difference_goals <- apply(left_right_head[5:6], 1, function(x) left_right(x))

left_right_head$difference <- apply(left_right_head[8:10], 1, function(x) sd(x))

left_right_head$xG_sum <- left_right_head$xG_sum_h + left_right_head$xG_sum_l + left_right_head$xG_sum_r

left_right_head$goal_sum <- left_right_head$goal_count_h + left_right_head$goal_count_l + left_right_head$goal_count_r

left_right_head$shot_sum <- left_right_head$shots_count_h + left_right_head$shots_count_l + left_right_head$shots_count_r

left_right_head$goal_for_shot <- left_right_head$shot_sum / left_right_head$goal_sum

left_right_head$difference_goals <- normalize(left_right_head$difference_goals)
left_right_head$difference_shots <- normalize(left_right_head$difference_shots)
left_right_head$difference <- normalize(left_right_head$difference)

left_right_head <- filter(left_right_head, goal_sum > 5)
```

```{r}
# write.csv(all_shots_with_ambidexteruty_index, file = '/content/Bundesliga_shots_2019_with_ambidexterity_v2.csv')
```

```{r}
left_right_head[order(left_right_head$difference),]
```

```{r}
filter(left_right_head, left_right_head$player == 'Robert Lewandowski')
```

```{r}
ggscatter(left_right_head, x = "difference", y = "xG_sum", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "<--Complete player Uses only one body part-->", ylab = "xG sum of a player")
```

```{r}
ggscatter(left_right_head, x = "difference", y = "goal_sum", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "<--Complete player Uses only one body part-->", ylab = "Goal sum of a player")
```

```{r}
ggscatter(left_right_head, x = "difference", y = "goal_for_shot", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "<--Complete player Uses only one body part-->", ylab = "Goal for shot")
```

